StudiPlataform/StudiPlataform/urls.py
"""
    StudiPlataform URL Configuration
"""
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

StudiPlataform/core/urls.py
from django.urls import path
from .import views as vs

app_name = 'core'

urlpatterns = [
    path('', vs.registrar, name='registrar'),
    path('listar', vs.listar, name='listar'),
]

StudiPlataform/core/models.py
from django.db import models

class RegistroModel(models.Model):
    nome = models.CharField('Nome Aluno', max_length=100)
    OPCOES_PROFESSOR = (
        ('Orlando Saraiva Jr', 'Orlando Saraiva Jr'),
        ('Thiago Mendes', 'Thiago Mendes'),
        ('Nilton', 'Nilton'),
        ('Sandro', 'Sandro'),
        ('Esdras', 'Esdras'),
        ('Ana Celia', 'Ana Celia'),
    )
    professor = models.CharField('Nome do Professor', max_length=100, choices=OPCOES_PROFESSOR)

    def __str__(self):
        return self.nome

StudiPlataform/core/forms.py
from django import forms
from core.models import RegistroModel
from django.forms import ModelForm

class RegistroForm(forms.Form):
    nome = forms.CharField(max_length=100)
    OPCOES_PROFESSOR = (
        ('Orlando Saraiva Jr', 'Orlando Saraiva Jr'),
        ('Thiago Mendes', 'Thiago Mendes'),
        ('Nilton', 'Nilton'),
        ('Sandro', 'Sandro'),
        ('Esdras', 'Esdras'),
        ('Ana Celia', 'Ana Celia'),
    )
    professor = forms.ChoiceField(choices=OPCOES_PROFESSOR)

    def clean_nome(self):
        nome = self.cleaned_data['nome']
        return nome.upper()
    
class RegistroModelForm(ModelForm):
    class Meta:
        model = RegistroModel
        fields = ['nome', 'professor']

    def clean_nome(self):
        nome = self.cleaned_data['nome']
        return nome.upper()
    

StudiPlataform/core/views.py
from django.shortcuts import redirect, render
from .forms import RegistroModelForm
from .models import RegistroModel

def registrar(request):
    if request.method == 'POST':
        form = RegistroModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('core:registrar')
    else:
        form = RegistroModelForm()
    return render(request, 'registrar.html', {'form': form})

def listar(request):
    professores = RegistroModel.OPCOES_PROFESSOR
    professor_escolhido = request.GET.get('professor', '')

    if professor_escolhido:
        alunos = RegistroModel.objects.filter(professor=professor_escolhido)
        contexto = {
            'professores': professores,
            'professor_escolhido': professor_escolhido,
            'alunos': alunos
        }
    else:
        contexto = {
            'professores': professores,
            'professor_escolhido': '',
            'alunos': []
        }

    return render(request, 'listar.html', contexto)

StudiPlataform/core/templates/listar.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>Lista de Presença</title>
</head>

<body>
      <header>
        <nav class="navbar navbar-expand-lg">
          <div class="container-fluid">
            <a class="navbar-brand" href="/" style="color:yellow">StudiPlataform</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/" style="color:white">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/listar" style="color:white">Lista de presença</a>
                </li>             
              </ul> 
            </div>
          </div>
        </nav>
    </header>
    <main>
        <h1 class="tittle-form">Lista de Presença</h1>
        <div class="content">
            <form class="form-listar" method="GET" action="{% url 'core:listar' %}">
                <p>
                <select name="professor">
                    <option value="">Selecione<br></option>
                    {% for professor in professores %}
                        <option value="{{ professor.0 }}" {% if professor_selecionado == professor.0 %}selected{% endif %}>{{ professor.1 }}</option>
                    {% endfor %}
                </select>
                <button class="btn-custom" type="submit">Listar</button>
                </p>
                <br>
            </form>
            <br>
        </div>

        <div>
            {% if professor_escolhido %}
                <h2 class="nome-professor">Professor: {{ professor_escolhido }}</h2>
                {% if alunos %}
                    <ul class="lista-alunos">
                        {% for aluno in alunos %}
                            {{ aluno.nome }}
                            <br>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p class="paragraph-selecione">Nenhum aluno registrado para esse professor.</p>
                {% endif %}
            {% else %}
                <p class="paragraph-selecione">Selecione um professor para listar os alunos.</p>
            {% endif %}
        </div>
    </main>
    <footer class="footer">
        <p>StudiPlataform &copy; 2023 Todos os direitos reservados.</p>
    </footer>
</body>

</html>

StudiPlataform/core/templates/registrar.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <title>Registro de presença no evento</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg">
          <div class="container-fluid">
            <a class="navbar-brand" href="/" style="color:yellow">StudiPlataform</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="/" style="color:white">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/listar" style="color:white">Lista de presença</a>
                </li>             
              </ul> 
            </div>
          </div>
        </nav>
    </header>
    <main>
      <section>
        <h1 class="tittle-form">Registro de presença no evento</h1>

            <form class="formulario" action="{% url 'core:registrar' %}" novalidate method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="nome-completo">Nome completo do aluno:</label>
                  {{ form.nome }}
                </div>
                <div class="form-group">
                  <label for="nome-professor">Nome do Professor:</label>
                  {{ form.professor }}
                </div>
                <input type="submit" class="btn-custom" value="Registrar">
            </form>              

      </section>
    </main>
    <footer class="footer">
        <p>StudiPlataform &copy; 2023 Todos os direitos reservados.</p>
    </footer>
</body>
</html>